### ISSUE TITLE
Cannot install to project

### ISSUE THREAD

**Issue by Sod3n** [actionk/Morpeh.Queries#1]
<img width="580" alt="image" src="https://github.com/actionk/Morpeh.Queries/assets/59008922/e35002aa-dcd0-4b73-aec8-5d947c92a8fe">

Unity version: 2021.3.30f1
Morpeh version: 2023.1.0

**Comment by actionk** [comment]
@Sod3n the library was updated to support Morpeh 2023.1 🤗
